plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ncm.decoder'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "2.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}
