apply plugin: 'com.android.application'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.ncmdecoder.pro"
        minSdkVersion 19
        targetSdkVersion 30
        versionCode 2
        versionName "2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    // 自动把 www/ 目录复制到 assets/
    task copyAssets(type: Copy) {
        from '../www'
        into 'src/main/assets'
        include '**/*'
    }
    preBuild.dependsOn copyAssets
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
